/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * Licensed under the Eclipse Foundation Specification License (EFSL).
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * SPDX-License-Identifier: EFSL-1.0
 */

@Library('releng-pipeline') _

// Avoid running the pipeline on branch indexing
if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
    print "INFO: Build skipped due to trigger being Branch Indexing"
    currentBuild.result = 'NOT_BUILT'
    return
}

pipeline {
    agent {
        label 'basic'
    }
    tools {
        maven 'apache-maven-3.9.11'
        jdk 'openjdk-jdk17-latest'
    }
    options {
        buildDiscarder logRotator(daysToKeepStr: '30', numToKeepStr: '10')
        disableConcurrentBuilds(abortPrevious: false)
    }
    parameters {
        string(
                name: 'RELEASE_VERSION',
                defaultValue: '',
                description: 'The version to be released, e.g. 1.0.0.',
                trim: true
        )
        string(
                name: 'DEVELOPMENT_VERSION',
                defaultValue: '',
                description: 'The next version to be used after the release, e.g. 1.0.1-SNAPSHOT.',
                trim: true
        )
        string(
                name: 'SPEC_STATUS',
                defaultValue: '',
                description: 'The specification status, e.g. DRAFT, BETA, etc., or blank for final.',
                trim: true
        )
    }
    stages {
        stage('Stage API to Eclipse Nexus') {
            when {
                beforeAgent true
                // Staging must be triggered explicitly
                triggeredBy cause: "UserIdCause"
            }
            steps {
                script {
                    if (!params.RELEASE_VERSION) {
                        throw new IllegalArgumentException("Missing value for parameter RELEASE_VERSION.")
                    }
                    if (!params.DEVELOPMENT_VERSION) {
                        throw new IllegalArgumentException("Missing value for parameter DEVELOPMENT_VERSION.")
                    }
                    echo "Staging release for version ${params.RELEASE_VERSION}"

                    sshagent(['github-bot-ssh', 'projects-storage.eclipse.org-bot-ssh']) {
                        withCredentials([file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING')]) {
                            withMaven(mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
                                sh "find . -type d -exec chmod -s {} \\;"
                                sh "find . -type d -exec chmod 0755 {} \\;"
                                sh 'mkdir -p ~/.gnupg && chmod 700 ~/.gnupg'
                                sh 'echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf'
                                sh 'gpgconf --kill gpg-agent || true'
                                sh 'gpg --batch --import "${KEYRING}"'
                                sh 'for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done'

                                // Set up git
                                sh 'git config --local user.name "agentic-ai-bot"'
                                sh 'git config --local user.email "agentic-ai-bot@eclipse.org"'

                                // Update version to release version
                                sh "mvn clean versions:set -DnewVersion=${params.RELEASE_VERSION} -DgenerateBackupPoms=false"

                                // Commit and tag the release version
                                sh "git commit -a -m '[Jenkins staging job] Preparing release ${params.RELEASE_VERSION}'"
                                sh "git tag -a -m 'Release ${params.RELEASE_VERSION}' ${params.RELEASE_VERSION}"

                                // Stage API to Eclipse Nexus (only api has maven.deploy.skip=false)
                                def nonFinalArg = params.SPEC_STATUS ? "" : "-Dspec.nonFinal=false"
                                sh "mvn clean deploy -Pstage-release -DskipTests=true ${nonFinalArg} -Dspec.status=${params.SPEC_STATUS}"

                                // Reset the version back to development
                                sh "mvn clean versions:set -DnewVersion=${params.DEVELOPMENT_VERSION} -DgenerateBackupPoms=false"

                                // Commit the dev version and push
                                sh "git commit -a -m '[Jenkins staging job] Preparing next development iteration'"
                                sh "git push origin HEAD:${env.GIT_BRANCH}"
                                sh "git push origin ${params.RELEASE_VERSION}"
                            }
                        }
                    }
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'api/target/reports/**/*',
                            fingerprint: true,
                            allowEmptyArchive: true
                }
            }
        }
    }
}
