/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * Licensed under the Eclipse Foundation Specification License (EFSL).
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * SPDX-License-Identifier: EFSL-1.0
 */

@Library('releng-pipeline') _

// Avoid running the pipeline on branch indexing
if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
    print "INFO: Build skipped due to trigger being Branch Indexing"
    currentBuild.result = 'NOT_BUILT'
    return
}

pipeline {
    agent {
        label 'basic'
    }
    tools {
        maven 'apache-maven-3.9.11'
        jdk 'openjdk-jdk17-latest'
    }
    options {
        buildDiscarder logRotator(daysToKeepStr: '30', numToKeepStr: '10')
        disableConcurrentBuilds(abortPrevious: false)
    }
    stages {
        stage('Promote Staged API to Maven Central') {
            when {
                beforeAgent true
                // Promotion must be triggered explicitly
                triggeredBy cause: "UserIdCause"
            }
            steps {
                script {
                    echo "Promoting staged artifacts from Eclipse Nexus to Maven Central"

                    withCredentials([file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING')]) {
                        withMaven(mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
                            sh "find . -type d -exec chmod -s {} \\;"
                            sh "find . -type d -exec chmod 0755 {} \\;"
                            sh 'gpg --batch --import "${KEYRING}"'
                            sh 'for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done'

                            // Promote from Eclipse Nexus staging to Maven Central
                            sh "mvn deploy -Ppromote-stage"
                        }
                    }
                }
            }
        }
    }
}
