/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */

@Library('releng-pipeline') _

if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
    print "INFO: Build skipped due to trigger being Branch Indexing"
    currentBuild.result = 'NOT_BUILT'
    return
}

pipeline {
    agent {
        label 'basic'
    }
    tools {
        maven 'apache-maven-3.9.11'
        jdk 'openjdk-jdk17-latest'
    }
    options {
        buildDiscarder logRotator(daysToKeepStr: '30', numToKeepStr: '10')
        disableConcurrentBuilds(abortPrevious: false)
    }
    stages {
        stage('Promote Staged API to Maven Central') {
            when {
                beforeAgent true
                triggeredBy cause: "UserIdCause"
            }
            steps {
                script {
                    echo "Promoting staged artifacts from Eclipse Nexus to Maven Central"

                    withCredentials([
                        file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING'),
                        string(credentialsId: 'gpg-passphrase', variable: 'MAVEN_GPG_PASSPHRASE')
                    ]) {
                        withMaven(mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
                            sh "find . -type d -exec chmod -s {} \\;"
                            sh "find . -type d -exec chmod 0755 {} \\;"
                            sh 'mkdir -p ~/.gnupg && chmod 700 ~/.gnupg'
                            sh 'echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf'
                            sh 'gpgconf --kill gpg-agent || true'
                            sh 'gpg --batch --import "${KEYRING}"'
                            sh 'for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done'

                            sh 'mvn deploy -Ppromote-stage'
                        }
                    }
                }
            }
        }
    }
}
