/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * Licensed under the Eclipse Foundation Specification License (EFSL).
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * SPDX-License-Identifier: EFSL-1.0
 */

@Library('releng-pipeline') _

// Avoid running the pipeline on branch indexing
if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
    print "INFO: Build skipped due to trigger being Branch Indexing"
    currentBuild.result = 'NOT_BUILT'
    return
}

pipeline {
    agent none
    options {
        // Wait for 1h before publishing snapshots, in case there are more commits
        quietPeriod 3600
        // Never publish snapshots more than once per hour
        rateLimitBuilds(throttle: [count: 1, durationName: 'hour', userBoost: true])
        buildDiscarder(logRotator(numToKeepStr: '3', artifactNumToKeepStr: '3'))
        disableConcurrentBuilds(abortPrevious: false)
    }
    stages {
        stage('Publish API Snapshots to Maven Central') {
            agent {
                label 'basic'
            }
            tools {
                maven 'apache-maven-3.9.11'
                jdk 'openjdk-jdk17-latest'
            }
            steps {
                script {
                    def currentVersion = sh(script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f api', returnStdout: true).trim()
                    if (currentVersion.endsWith("-SNAPSHOT")) {
                        withCredentials([file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING')]) {
                            withMaven(mavenLocalRepo: env.WORKSPACE_TMP + '/.m2repository') {
                                sh "find . -type d -exec chmod -s {} \\;"
                                sh "find . -type d -exec chmod 0755 {} \\;"
                                sh 'gpg --batch --import "${KEYRING}"'
                                sh 'for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done'

                                // Deploy API snapshot (only api has maven.deploy.skip=false)
                                sh "mvn clean deploy -Poss-release -Psnapshots -DskipTests=true"
                            }
                        }
                    } else {
                        echo "Current ref is not a snapshot: ${currentVersion}. Nothing to deploy!"
                    }
                }
            }
        }
    }
}
